---
title: "Exploration"
author: "Saul Widrich"
date: "2024-05-03"
output: rmarkdown::github_document
---
# Load required packages
```{r setup, include=FALSE}
library(iidda.api)  
library(dplyr)      
```
# Retrieve and filter data
```{r, message=FALSE}
api_hook <- iidda.api::ops_staging
cdi <- api_hook$filter(
    resource_type = "CANMOD CDI",
    iso_3166 = "CA"
)
```   

# Perform data analysis using the pipe operator
```{r}
measles_wk_on <- cdi %>%
  filter(disease == "measles", iso_3166_2 == "CA-ON", time_scale == "wk") %>%
  mutate(daily_rate = 10^5 * cases_this_period / (days_this_period * population),
         years_since_first_observation = as.numeric((period_start_date - min(period_start_date)) / (365.25)))
```
# Periodogram (both frequency and period)

```{r}
periodogram <- lomb::lsp(measles_wk_on$years_since_first_observation, measles_wk_on$daily_rate, type = 'period', plot = "True")

periodogram <- lomb::lsp(measles_wk_on$years_since_first_observation, measles_wk_on$daily_rate, type = 'frequency', plot = "True")
```
